add support to use the entire file
ThisIsSecurity/retdec_offline pull request #3
Opened 2018-04-10 18:07 UTC by psifertex

Fixes the problems described in #2.

I'm not sure whether just switching entirely to the new method is better (maybe not for large files?) so for now I just register two menu items, but it's a pretty quick implementation. Feel free to change any way you like or let me know if you have other preferences.

2018-04-11 13:30 UTC, paulfariello commented
Thanks for the PR. I'm doing a quick review right now.
I agree on giving the user the choice of decompiling only a function or the full binary.

2018-04-11 13:45 UTC, paulfariello requested changes
Thanks for the PR just a few minor things to fix and I'll merge it.

2018-04-11 13:45 UTC, paulfariello commented on __init__.py
> +        self.cmdline = ['retdec-decompiler.sh']
You must init cmdline before appending `'-m'` and `mode`. Better remove your last commit.

2018-04-11 13:45 UTC, paulfariello commented on __init__.py
> +        self.render_output(code)
We shouldn't dup the code between the two `decompile_` functions.

2018-04-11 13:45 UTC, paulfariello commented on __init__.py
> +        os.unlink('{}.c.frontend.dsm'.format(filename))
We must remove filename too.

2018-04-11 13:45 UTC, paulfariello commented on __init__.py
> +        return filename
This function is duplicated it appears twice. See just below.

2018-04-11 13:45 UTC, paulfariello commented on __init__.py
> +        log_error('failed to decompile function\n{}'.format(e.message))
Should fix the log error: `failed to decompile file`.

2018-04-11 13:45 UTC, paulfariello commented on __init__.py
> +        self.cmdline.append('{:#x}-{:#x}'.format(start, start+1))
Don't know if this is the right way to pass the range. But I haven't tested it and it just seems odd.

2018-04-11 15:01 UTC, paulfariello commented
Could you rebase your PR onto develop ? I've added travis-ci and pylint automation.

2018-04-19 18:20 UTC, psifertex commented on __init__.py
> +        self.cmdline.append('{:#x}-{:#x}'.format(start, start+1))
Worked in testing and looks correct according to their examples: https://github.com/avast-tl/retdec/blob/master/scripts/retdec-decompiler.sh#L84

2018-04-19 21:52 UTC, psifertex commented
Sorry about that, wasn't getting these notifications. I think I resolved all the issues. Squashed and rebased on dev.

One minor clarification -- I didn't change it to actually decompile the entire binary right now, it just passes the entire binary to retdec and specifies the specific function since otherwise a lot of important context is lost that breaks disassembly even for that function (see issue #2 for example). I just call it "full" or "slower" analysis for the time being, but it might be worth documenting in the readme what the differences are. 

Travis failed, but it doesn't look like anything I'm doing as far as I can tell?

2018-04-25 16:37 UTC, nallar commented on __init__.py
> +        #Doesn't just operate on the original file since in a .BNDB the original file may no longer exist
This line and 167 are too long so it's failing pylint

2018-05-04 15:47 UTC, paulfariello approved these changes

2018-05-04 15:50 UTC, paulfariello commented
I rebased your PR onto develop since there was some rewrite of the plugin to support retdec config file.
Only one question left, ishould we decompile on range `function.start, function.start+1` or on full function?

2018-05-04 15:57 UTC, psifertex commented
Thanks. Sorry I was slow to get back to this. 

I used `select-ranges` because `select-function` required knowing the function name as opposed to an address, but specifying the start address of a specific function seems to result in just that function being decompiled, so believe that's the right choice but could be wrong. 

I don't think it would hurt to do start to start+1 (though I don't think it will help, either), but "full function" is a bit problematic. Mainly because there's no real definition of what that would be. If you chose the lowest address to the highest address it's possible to have interleaved basic blocks (most compilers don't do this, but there's no reason they couldn't) so another function not desired to be decompiled could also be decompiled.

2018-05-04 16:09 UTC, merged